### ISSUE TITLE
Unable to select a theme

### ISSUE THREAD

**Issue by antoinec4** [FiercestT/EasyEdaThemes#13]
Hi,

Altough my main theme has changed when loading the extension, it looks like I can't select a theme, given the steps provided in your ReadMe :

Take a look :

![image](https://user-images.githubusercontent.com/124214296/221719353-c51a8627-b2aa-4c82-a206-b43ab4dd6b40.png)

![image](https://user-images.githubusercontent.com/124214296/221719423-4bd77849-3a5e-4a04-ab32-9faca2610c51.png)

I'm on EasyEDA STD 6.5.22 as you can see.
Am I missing something ?

Thanks,

**Comment by FiercestT** [comment]
Hi, after loading the extension you should get an additional option at the top row as shown in the image below. 

![image](https://user-images.githubusercontent.com/46426125/221721322-d8268c5d-32d0-40be-a446-4e3cbe4f8531.png)

**Comment by antoinec4** [comment]
Thank you for the responsiveness, I simply didn't notice it.
