### ISSUE TITLE
Theme removes styles from other Extensions

### ISSUE THREAD

**Issue by xsrf** [FiercestT/EasyEdaThemes#2]
Hey,
I noticed that your extension actually removes all styles from the page in order to apply the themes.
This also impacts other extensions which use additional styles for their UI, like 

https://github.com/xsrf/easyeda-labelmaker :

![2021-03-16 16_59_06-EasyEDA(Standard) - A Simple and Powerful Electronic Circuit Design Tool](https://user-images.githubusercontent.com/8081353/111340759-35666580-8679-11eb-8f29-5a2a0a5188e8.png)
![2021-03-16 16_59_22-EasyEDA(Standard) - A Simple and Powerful Electronic Circuit Design Tool](https://user-images.githubusercontent.com/8081353/111340761-35fefc00-8679-11eb-8287-17916be7093f.png)

(alignment and fieldset style gets lost)

Or https://github.com/turbobabr/easyeda-qrcode-generator-extension by @turbobabr :

![2021-03-16 16_58_46-EasyEDA(Standard) - A Simple and Powerful Electronic Circuit Design Tool](https://user-images.githubusercontent.com/8081353/111340876-4e6f1680-8679-11eb-9240-2c6adfdb23a9.png)
![2021-03-16 16_58_54-EasyEDA(Standard) - A Simple and Powerful Electronic Circuit Design Tool](https://user-images.githubusercontent.com/8081353/111340879-4e6f1680-8679-11eb-80a9-75f794b27479.png)

(preview area and buttons get lost)

See also: https://github.com/turbobabr/easyeda-ibom-extension/issues/1#issuecomment-800191219

Maybe you can narrow down the selection of styles to remove to only known ones, so you don't remove others?

**Comment by FiercestT** [comment]
I see,
It shouldn't override those attributes (just colors really), but as you pointed out I remove styling. Honestly forgot why I did that considering all my css has !important (P.S. I'm not really a JS/CSS dev). 
This happened because I didn't have any custom extensions when developing this, but I'll fix it on the weekend.

**Comment by xsrf** [comment]
I haven't had a look at the EasyEDA styles and how they work, but usually it is enough to inject your override styles after the original styles.

**Comment by FiercestT** [comment]
I believe I had this at one point, it was a late night finishing this up though so something must have happened.

**Comment by FiercestT** [comment]
Fixed thanks to @vlrmprjct on PR #3.

**Comment by turbobabr** [comment]
Thank you guys for resolving this! 🙏
